spring:
  application:
    name: ante_room_crawling
  jackson:
    time-zone: Asia/Seoul

  datasource:
    url: jdbc:mariadb://localhost:3303/crawling_db
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: true
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    web: DEBUG

server:
  port: 8085

webdriver:
  chrome:
    path: ./driver/chromedriver.exe

scheduler:
  cron:
    crawling: 0 0/1 * * * ?
