spring:
  datasource:
    url: jdbc:mariadb://ec2-43-201-148-105.ap-northeast-2.compute.amazonaws.com:3306/crawling_db
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    web: INFO

webdriver:
  chrome:
    path: /usr/local/bin/chromedriver

scheduler:
  cron:
    crawling: 0 0/30 8-19 * * MON-FRI
