spring:
  datasource:
    url: jdbc:mariadb://3.39.0.84:3306/crawling_db
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    web: INFO

server:
  port: 8080
  enabled: true
  key-store-type: PEM
  certificate: /etc/letsencrypt/live/anteroom.org/fullchain.pem
  certificate-private-key: /etc/letsencrypt/live/anteroom.org/privkey.pem

webdriver:
  chrome:
    path: /usr/local/bin/chromedriver

scheduler:
  cron:
    crawling: 0 0 8-19 * * MON-FRI # 월-금 8시부터 19시까지 매시간 정각에 실행
